repositoriesListing:
  blacklist: []
  whitelist: [
    package-deployer,
    node-app,
    configuration,
    home,
    la-barquita,
    react-navbar,
    notes-3,
    ui,
    default-config,
    react-hooks,
    types,
    rest-api,
    python-labs,
    backend,
    react-utils,
    models,
    backend-services,
    personal-log-mui,
    perseverancia,
    package-manager,
    utils,
    local-storage,
    system-user,
    port-seeker,
    verdaccio-client,
    git-manager,
    app-manager-lib,
    node-filesystem,
    mental-health,
    docs,
    app-manager,
    admin-dashboard,
    minecraft-launcher,
    scripts,
    pid-discovery,
    desktop-entry,
    apps,
    systemd-unit,
    deployment-state,
    global-event-manager,
    class-gatherer,
    backup,
    mysql-database-manager,
    folder-sync,
    env,
    database-seeding,
    backend-utils,
    app-processes,
    monorepo-sharding,
    development-package-manager,
    package-discovery,
    objects-container,
    env-file,
    perseverancia-nextui,
    personal-backend,
    threejs-minecraft,
    task-scheduler,
    youtube-playlist-downloader,
    clinic-frontend,
    meeti-nextjs,
    minecraft-scripts
  ]
  use: whitelist
