repositoriesListing:
  blacklist: []
  whitelist: [
    admin-dashboard,
    app-manager-lib,
    app-manager,
    app-processes,
    apps,
    backend-utils,
    backup,
    class-gatherer,
    clinic-frontend,
    configuration,
    default-config,
    database-seeding,
    deployment-state,
    desktop-entry,
    development-package-manager,
    docs,
    env-file,
    env,
    folder-sync,
    game-inventory,
    global-event-manager,
    home,
    la-barquita,
    mental-health,
    node-app,
    node-filesystem,
    notes-3,
    package-deployer,
    python-labs,
    backend,
    mysql-database-manager,
    meeti-nextjs,
    minecraft-scripts
    models,
    monorepo-sharding,
    backend-services,
    personal-log-mui,
    perseverancia,
    package-manager,
    local-storage,
    port-seeker,
    verdaccio-client,
    git-manager,
    minecraft-launcher,
    pid-discovery,
    systemd-unit,
    objects-container,
    package-discovery,
    perseverancia-nextui,
    personal-backend,
    react-utils,
    react-navbar,
    react-hooks,
    rest-api,
    rust-transpiler,
    scripts,
    system-user,
    task-scheduler,
    threejs-minecraft,
    types,
    voxel-odyssey-backend,
    voxel-odyssey-engine,
    ui,
    utils,
    youtube-playlist-downloader,
  ]
  use: whitelist
